dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - libgccjit-5-dev
      - texinfo
      - gdb

install:
  - export CXX="g++-5" CC="gcc-5"
  - export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/gcc/x86_64-linux-gnu/5 #:$TRAVIS_BUILD_DIR/install/lib
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/install/lib:$LD_LIBRARY_PATH

before_script:
  # Build GNU Lightning
  - cd $TRAVIS_BUILD_DIR
  - wget http://git.savannah.gnu.org/cgit/lightning.git/snapshot/lightning-2.1.2.tar.gz
  - tar xzf lightning-2.1.2.tar.gz
  - cd lightning-2.1.2 && autoreconf -i && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install
  # Build LibJIT
  - cd $TRAVIS_BUILD_DIR
  - git clone --depth=1 https://git.savannah.gnu.org/git/libjit.git
  - cd libjit && ./bootstrap && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install
  - cd $TRAVIS_BUILD_DIR
  # enable core dumps
  - ulimit -c unlimited -S

script:
  - make test JIT=sljit CXXFLAGS='-g -O0'
  - ./test
  - make test JIT=lightning CXXFLAGS='-g -O0' LDFLAGS="-L$TRAVIS_BUILD_DIR/install/lib -llightning" CPPFLAGS=-I$TRAVIS_BUILD_DIR/install/include
  - ./test
  - make test JIT=libjit CXXFLAGS='-g -O0' LDFLAGS="-L$TRAVIS_BUILD_DIR/install/lib -ljit" CPPFLAGS=-I$TRAVIS_BUILD_DIR/install/include
  - ./test
  - make test JIT=gccjit CXXFLAGS='-g -O0'
  - ./test

after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
  - rm $COREFILE
