dist: xenial
sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgccjit-5-dev
      - texinfo

install:
  - export CXX="g++-5" CC="gcc-5"
  - export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/gcc/x86_64-linux-gnu/5 #:$TRAVIS_BUILD_DIR/install/lib
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/install/lib:$LD_LIBRARY_PATH

before_script:
  # Build GNU Lightning
  - cd $TRAVIS_BUILD_DIR
  - wget http://git.savannah.gnu.org/cgit/lightning.git/snapshot/lightning-2.1.2.tar.gz
  - tar xzf lightning-2.1.2.tar.gz
  - cd lightning-2.1.2 && autoreconf -i && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install
  # Build LibJIT
  - cd $TRAVIS_BUILD_DIR
  - wget http://git.savannah.gnu.org/cgit/libjit.git/snapshot/libjit-0.1.4.tar.gz
  - tar xzf libjit-0.1.4.tar.gz
  - cd libjit-0.1.4 && ./bootstrap && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install
  - export LIBJIT_DIR=$TRAVIS_BUILD_DIR/install
  # done
  - cd $TRAVIS_BUILD_DIR

script:
  - make unittests
  - ./unittests
