dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - texinfo

install:
  - export CXX="g++-5" CC="gcc-5"

before_script:
  # Build GNU Lightning
  - cd $TRAVIS_BUILD_DIR
  - wget http://git.savannah.gnu.org/cgit/lightning.git/snapshot/lightning-2.1.2.tar.gz
  - tar xzf lightning-2.1.2.tar.gz
  - cd lightning-2.1.2 && autoreconf -i && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install
  # Build LibJIT
  - cd $TRAVIS_BUILD_DIR
  - git clone --depth=1 https://git.savannah.gnu.org/git/libjit.git
  - cd libjit && ./bootstrap && ./configure --prefix=$TRAVIS_BUILD_DIR/install
  - make && make install

script:
  - cd $TRAVIS_BUILD_DIR
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/install/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/install/lib:$LIBRARY_PATH
  - make test JIT=sljit
  - ./test
  - make test JIT=lightning LDFLAGS="-L$TRAVIS_BUILD_DIR/install/lib -llightning" CPPFLAGS=-I$TRAVIS_BUILD_DIR/install/include
  - ./test
  - make test JIT=libjit LDFLAGS="-L$TRAVIS_BUILD_DIR/install/lib -ljit" CPPFLAGS=-I$TRAVIS_BUILD_DIR/install/include
  - ./test
